enum TrackEvents {
    loaded = 'loaded',
    loadedAgain = 'loadedAgain',
    beginSurveys = 'beginSurveys',
    questionSection = 'questionSection',
    teenLead = 'teenLead',
    lead = 'lead',
    motivated = 'motivated',
    notMotivated = 'notMotivated',
    photoExit = 'photoExit',
    autoExit = 'autoExit',
    reverseExit = 'reverseExit',
    accessAutoExit = 'accessAutoExit',
    nonUnique = 'nonUnique',
    notInterested = 'notInterested',
    backButtonExit = 'backButtonExit',
}