export enum TrackEvents {
    loaded = 'loaded',
    loadedAgain = 'loadedAgain',
    beginSurveys = 'beginSurveys',
    questionSection = 'questionSection',
    teenLead = 'teenLead',
    lead = 'lead',
    motivated = 'motivated',
    notMotivated = 'notMotivated',
    photoExit = 'photoExit',
    autoExit = 'autoExit',
    reverseExit = 'reverseExit',
    accessAutoExit = 'accessAutoExit',
    nonUnique = 'nonUnique',
    notInterested = 'notInterested',
    backButtonExit = 'backButtonExit',
    nonUniqueAutoExit = 'nonUniqueAutoExit',
    alreadyAccessAutoExit = 'alreadyAccessAutoExit',
}

export enum GameEvents {
    playAgain = 'playAgain',
    requestLeaderboard = 'requestLeaderboard',
    getMoreHint = 'getMoreHint',
    vignetteGameOver = 'vignetteGameOver',
    vignetteImpression = 'vignetteImpression',
    vignetteProxy = 'vignetteProxy',
    vignetteLead = 'vignetteLead',
    vignetteClose = 'vignetteClose',
    showHint = 'showHint',
    userCreated = 'userCreated',
    userExists = 'userExists',
    lostOnTime = 'lostOnTime',
    lostByWrongAnswer = 'lostByWrongAnswer',
    firstTimeGame = 'firstTimeGame',
    firstTimeGameOver = 'firstTimeGameOver',
    firstTimeLeaderboard = 'firstTimeLeaderboard',
    clickedOnVignetteImage = 'clickedOnVignetteImage',
    endOfGame = 'endOfGame',
}