import { inter, interBold } from '@/fonts/Fonts';
import StyledComponentsRegistry from '@/lib/SCregistry';
import { Providers } from './Providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' className={`${interBold.variable} ${inter.variable}`}>
      <StyledComponentsRegistry>
        <Providers>
          <body>{children}</body>
        </Providers>
      </StyledComponentsRegistry>
    </html>
  );
}
