export const travelReviews = [
  {
    id: 1,
    title: 'This is the best white t-shirt out there',
    text: "I've searched my entire life for a t-shirt that reflects every color in the visible spectrum. Scientists said it couldn't be done, but when I look at this shirt, I see white light bouncing right back into my eyes. Incredible!",
    likes: 10,
    rating: 5,
    personImage: '/images/reviewers/female.webp',
    personName: 'Emily Selman',
    winImages: [
      '/images/travel/travelReviews/singapore101.webp',
      '/images/travel/travelReviews/singapore102.webp',
      '/images/travel/travelReviews/singapore103.webp',
      '/images/travel/travelReviews/singapore104.webp',
    ],
  },
  {
    id: 2,
    title: 'This is the best white t-shirt out there',
    text: "I've searched my entire life for a t-shirt that reflects every color in the visible spectrum. Scientists said it couldn't be done, but when I look at this shirt, I see white light bouncing right back into my eyes. Incredible!",
    likes: 10,
    rating: 5,
    personImage: '/images/reviewers/female2.webp',
    personName: 'Emily Selman',
    winImages: [
      '/images/travel/travelReviews/singapore105.webp',
      '/images/travel/travelReviews/singapore106.webp',
    ],
  },
  {
    id: 3,
    title: 'This is the best white t-shirt out there',
    text: "I've searched my entire life for a t-shirt that reflects every color in the visible spectrum. Scientists said it couldn't be done, but when I look at this shirt, I see white light bouncing right back into my eyes. Incredible!",
    likes: 10,
    rating: 5,
    personImage: '/images/reviewers/female3.webp',
    personName: 'Emily Selman',
    winImages: [
      '/images/travel/travelReviews/singapore107.webp',
      '/images/travel/travelReviews/singapore108.webp',
    ],
  },
  {
    id: 4,
    title: 'This is the best white t-shirt out there',
    text: "I've searched my entire life for a t-shirt that reflects every color in the visible spectrum. Scientists said it couldn't be done, but when I look at this shirt, I see white light bouncing right back into my eyes. Incredible!",
    likes: 10,
    rating: 5,
    personImage: '/images/reviewers/female4.webp',
    personName: 'Emily Selman',
  },
  {
    id: 5,
    title: 'This is the best white t-shirt out there',
    text: "I've searched my entire life for a t-shirt that reflects every color in the visible spectrum. Scientists said it couldn't be done, but when I look at this shirt, I see white light bouncing right back into my eyes. Incredible!",
    likes: 10,
    rating: 5,
    personImage: '/images/reviewers/female5.webp',
    personName: 'Emily Selman',
  },
];
