export interface ICountry {
  id: number;
  name: string;
  flag: string;
  iso2: string;
  iso3?: string;
  population: number;
}
const countries: ICountry[] = [
  {
    id: 1,
    name: 'Afghanistan',
    flag: '/images/countries/Flag_of_the_Taliban.svg',
    iso2: 'AF',
    iso3: 'AFG',
    population: 37172386,
  },
  {
    id: 2,
    name: 'Albania',
    flag: '/images/countries/Flag_of_Albania.svg',
    iso2: 'AL',
    iso3: 'ALB',
    population: 2866376,
  },
  {
    id: 3,
    name: 'Algeria',
    flag: '/images/countries/Flag_of_Algeria.svg',
    iso2: 'DZ',
    iso3: 'DZA',
    population: 42228429,
  },
  {
    id: 4,
    name: 'Andorra',
    flag: '/images/countries/Flag_of_Andorra.svg',
    iso2: 'AD',
    iso3: 'AND',
    population: 77006,
  },
  {
    id: 5,
    name: 'Angola',
    flag: '/images/countries/Flag_of_Angola.svg',
    iso2: 'AO',
    iso3: 'AGO',
    population: 30809762,
  },
  {
    id: 7,
    name: 'Antigua and Barbuda',
    flag: '/images/countries/Flag_of_Antigua_and_Barbuda.svg',
    iso2: 'AG',
    iso3: 'ATG',
    population: 96286,
  },
  {
    id: 8,
    name: 'Argentina',
    flag: '/images/countries/Flag_of_Argentina.svg',
    iso2: 'AR',
    iso3: 'ARG',
    population: 44494502,
  },
  {
    id: 9,
    name: 'Armenia',
    flag: '/images/countries/Flag_of_Armenia.svg',
    iso2: 'AM',
    iso3: 'ARM',
    population: 2951776,
  },
  {
    id: 10,
    name: 'Aruba',
    flag: '/images/countries/Flag_of_Aruba.svg',
    iso2: 'AW',
    iso3: 'ABW',
    population: 105845,
  },
  {
    id: 11,
    name: 'Australia',
    flag: '/images/countries/Flag_of_Australia.svg',
    iso2: 'AU',
    iso3: 'AUS',
    population: 24982688,
  },
  {
    id: 12,
    name: 'Austria',
    flag: '/images/countries/Flag_of_Austria.svg',
    iso2: 'AT',
    iso3: 'AUT',
    population: 8840521,
  },
  {
    id: 13,
    name: 'Azerbaijan',
    flag: '/images/countries/Flag_of_Azerbaijan.svg',
    iso2: 'AZ',
    iso3: 'AZE',
    population: 9939800,
  },
  {
    id: 14,
    name: 'Bahamas',
    flag: '/images/countries/Flag_of_the_Bahamas.svg',
    iso2: 'BS',
    iso3: 'BHS',
    population: 385640,
  },
  {
    id: 15,
    name: 'Bahrain',
    flag: '/images/countries/Flag_of_Bahrain.svg',
    iso2: 'BH',
    iso3: 'BHR',
    population: 1569439,
  },
  {
    id: 16,
    name: 'Bangladesh',
    flag: '/images/countries/Flag_of_Bangladesh.svg',
    iso2: 'BD',
    iso3: 'BGD',
    population: 161356039,
  },
  {
    id: 17,
    name: 'Barbados',
    flag: '/images/countries/Flag_of_Barbados.svg',
    iso2: 'BB',
    iso3: 'BRB',
    population: 286641,
  },
  {
    id: 18,
    name: 'Belarus',
    flag: '/images/countries/Flag_of_Belarus.svg',
    iso2: 'BY',
    iso3: 'BLR',
    population: 9483499,
  },
  {
    id: 19,
    name: 'Belgium',
    flag: '/images/countries/Flag_of_Belgium.svg',
    iso2: 'BE',
    iso3: 'BEL',
    population: 11433256,
  },
  {
    id: 20,
    name: 'Belize',
    flag: '/images/countries/Flag_of_Belize.svg',
    iso2: 'BZ',
    iso3: 'BLZ',
    population: 383071,
  },
  {
    id: 21,
    name: 'Benin',
    flag: '/images/countries/Flag_of_Benin.svg',
    iso2: 'BJ',
    iso3: 'BEN',
    population: 11485048,
  },
  {
    id: 22,
    name: 'Bermuda',
    flag: '/images/countries/Flag_of_Bermuda.svg',
    iso2: 'BM',
    iso3: 'BMU',
    population: 63973,
  },
  {
    id: 23,
    name: 'Bhutan',
    flag: '/images/countries/Flag_of_Bhutan.svg',
    iso2: 'BT',
    iso3: 'BTN',
    population: 754394,
  },
  {
    id: 24,
    name: 'Bosnia and Herzegovina',
    flag: '/images/countries/Flag_of_Bosnia_and_Herzegovina.svg',
    iso2: 'BA',
    iso3: 'BIH',
    population: 3323929,
  },
  {
    id: 25,
    name: 'Botswana',
    flag: '/images/countries/Flag_of_Botswana.svg',
    iso2: 'BW',
    iso3: 'BWA',
    population: 2254126,
  },
  {
    id: 27,
    name: 'Brazil',
    flag: 'images/countries/Flag_of_Brazil.svg',
    iso2: 'BR',
    iso3: 'BRA',
    population: 209469333,
  },
  {
    id: 29,
    name: 'Brunei',
    flag: '/images/countries/Flag_of_Brunei.svg',
    iso2: 'BN',
    iso3: 'BRN',
    population: 428962,
  },
  {
    id: 30,
    name: 'Bulgaria',
    flag: '/images/countries/Flag_of_Bulgaria.svg',
    iso2: 'BG',
    iso3: 'BGR',
    population: 7025037,
  },
  {
    id: 31,
    name: 'Burkina Faso',
    flag: '/images/countries/Flag_of_Burkina_Faso.svg',
    iso2: 'BF',
    iso3: 'BFA',
    population: 19751535,
  },
  {
    id: 32,
    name: 'Burundi',
    flag: '/images/countries/Flag_of_Burundi.svg',
    iso2: 'BI',
    iso3: 'BDI',
    population: 11175378,
  },
  {
    id: 33,
    name: 'Cambodia',
    flag: '/images/countries/Flag_of_Cambodia.svg',
    iso2: 'KH',
    iso3: 'KHM',
    population: 16249798,
  },
  {
    id: 34,
    name: 'Cameroon',
    flag: '/images/countries/Flag_of_Cameroon.svg',
    iso2: 'CM',
    iso3: 'CMR',
    population: 25216237,
  },
  {
    id: 35,
    name: 'Canada',
    flag: 'images/countries/Flag_of_Canada.svg',
    iso2: 'CA',
    iso3: 'CAN',
    population: 37057765,
  },
  {
    id: 36,
    name: 'Cape Verde',
    flag: '/images/countries/Flag_of_Cape_Verde.svg',
    iso2: 'CV',
    iso3: 'CPV',
    population: 543767,
  },
  {
    id: 37,
    name: 'Cayman Islands',
    flag: '/images/countries/Flag_of_the_Cayman_Islands.svg',
    iso2: 'KY',
    iso3: 'CYM',
    population: 64174,
  },
  {
    id: 38,
    name: 'Central African Republic',
    flag: '/images/countries/Flag_of_the_Central_African_Republic.svg',
    iso2: 'CF',
    iso3: 'CAF',
    population: 4666377,
  },
  {
    id: 39,
    name: 'Chad',
    flag: '/images/countries/Flag_of_Chad.svg',
    iso2: 'TD',
    iso3: 'TCD',
    population: 15477751,
  },
  {
    id: 40,
    name: 'Chile',
    flag: '/images/countries/Flag_of_Chile.svg',
    iso2: 'CL',
    iso3: 'CHL',
    population: 18729160,
  },
  {
    id: 41,
    name: 'China',
    flag: '/images/countries/Flag_of_the_China.svg',
    iso2: 'CN',
    iso3: 'CHN',
    population: 1392730000,
  },
  {
    id: 44,
    name: 'Colombia',
    flag: '/images/countries/Flag_of_Colombia.svg',
    iso2: 'CO',
    iso3: 'COL',
    population: 49648685,
  },
  {
    id: 45,
    name: 'Comoros',
    flag: '/images/countries/Flag_of_the_Comoros.svg',
    iso2: 'KM',
    iso3: 'COM',
    population: 832322,
  },
  {
    id: 46,
    name: 'Congo',
    flag: '/images/countries/Flag_of_the_Republic_of_the_Congo.svg',
    iso2: 'CG',
    iso3: 'COG',
    population: 5244363,
  },
  {
    id: 48,
    name: 'Costa Rica',
    flag: '/images/countries/Flag_of_Costa_Rica.svg',
    iso2: 'CR',
    iso3: 'CRI',
    population: 4999441,
  },
  {
    id: 49,
    name: 'Croatia',
    flag: '/images/countries/Flag_of_Croatia.svg',
    iso2: 'HR',
    iso3: 'HRV',
    population: 4087843,
  },
  {
    id: 50,
    name: 'Cuba',
    flag: '/images/countries/Flag_of_Cuba.svg',
    iso2: 'CU',
    iso3: 'CUB',
    population: 11338138,
  },
  {
    id: 51,
    name: 'Cyprus',
    flag: '/images/countries/Flag_of_Cyprus.svg',
    iso2: 'CY',
    iso3: 'CYP',
    population: 1189265,
  },
  {
    id: 52,
    name: 'Czech Republic',
    flag: '/images/countries/Flag_of_the_Czech_Republic.svg',
    iso2: 'CZ',
    iso3: 'CZE',
    population: 10629928,
  },
  {
    id: 53,
    name: 'Denmark',
    flag: '/images/countries/Flag_of_Denmark.svg',
    iso2: 'DK',
    iso3: 'DNK',
    population: 5793636,
  },
  {
    id: 54,
    name: 'Djibouti',
    flag: '/images/countries/Flag_of_Djibouti.svg',
    iso2: 'DJ',
    iso3: 'DJI',
    population: 958920,
  },
  {
    id: 55,
    name: 'Dominica',
    flag: '/images/countries/Flag_of_Dominica.svg',
    iso2: 'DM',
    iso3: 'DMA',
    population: 71625,
  },
  {
    id: 56,
    name: 'Dominican Republic',
    flag: '/images/countries/Flag_of_the_Dominican_Republic.svg',
    iso2: 'DO',
    iso3: 'DOM',
    population: 10627165,
  },
  {
    id: 57,
    name: 'Ecuador',
    flag: '/images/countries/Flag_of_Ecuador.svg',
    iso2: 'EC',
    iso3: 'ECU',
    population: 17084357,
  },
  {
    id: 58,
    name: 'Egypt',
    flag: '/images/countries/Flag_of_Egypt.svg',
    iso2: 'EG',
    iso3: 'EGY',
    population: 98423595,
  },
  {
    id: 59,
    name: 'El Salvador',
    flag: '/images/countries/Flag_of_El_Salvador.svg',
    iso2: 'SV',
    iso3: 'SLV',
    population: 6420744,
  },
  {
    id: 60,
    name: 'Equatorial Guinea',
    flag: '/images/countries/Flag_of_Equatorial_Guinea.svg',
    iso2: 'GQ',
    iso3: 'GNQ',
    population: 1308974,
  },
  {
    id: 62,
    name: 'Estonia',
    flag: '/images/countries/Flag_of_Estonia.svg',
    iso2: 'EE',
    iso3: 'EST',
    population: 1321977,
  },
  {
    id: 63,
    name: 'Ethiopia',
    flag: '/images/countries/Flag_of_Ethiopia.svg',
    iso2: 'ET',
    iso3: 'ETH',
    population: 109224559,
  },
  {
    id: 65,
    name: 'Faroe Islands',
    flag: '/images/countries/Flag_of_the_Faroe_Islands.svg',
    iso2: 'FO',
    iso3: 'FRO',
    population: 48497,
  },
  {
    id: 66,
    name: 'Fiji',
    flag: '/images/countries/Flag_of_Fiji.svg',
    iso2: 'FJ',
    iso3: 'FJI',
    population: 883483,
  },
  {
    id: 67,
    name: 'Finland',
    flag: '/images/countries/Flag_of_Finland.svg',
    iso2: 'FI',
    iso3: 'FIN',
    population: 5515525,
  },
  {
    id: 68,
    name: 'France',
    flag: 'images/countries/Flag_of_France.svg',
    iso2: 'FR',
    iso3: 'FRA',
    population: 66977107,
  },
  {
    id: 69,
    name: 'French Polynesia',
    flag: '/images/countries/Flag_of_French_Polynesia.svg',
    iso2: 'PF',
    iso3: 'PYF',
    population: 277679,
  },
  {
    id: 70,
    name: 'Gabon',
    flag: '/images/countries/Flag_of_Gabon.svg',
    iso2: 'GA',
    iso3: 'GAB',
    population: 2119275,
  },
  {
    id: 71,
    name: 'Gambia',
    flag: '/images/countries/Flag_of_The_Gambia.svg',
    iso2: 'GM',
    iso3: 'GMB',
    population: 2280102,
  },
  {
    id: 72,
    name: 'Georgia',
    flag: '/images/countries/Flag_of_Georgia.svg',
    iso2: 'GE',
    iso3: 'GEO',
    population: 3726549,
  },
  {
    id: 73,
    name: 'Germany',
    flag: 'images/countries/Flag_of_Germany.svg',
    iso2: 'DE',
    iso3: 'DEU',
    population: 82905782,
  },
  {
    id: 74,
    name: 'Ghana',
    flag: '/images/countries/Flag_of_Ghana.svg',
    iso2: 'GH',
    iso3: 'GHA',
    population: 29767108,
  },
  {
    id: 75,
    name: 'Gibraltar',
    flag: '/images/countries/Flag_of_Gibraltar.svg',
    iso2: 'GI',
    iso3: 'GIB',
    population: 33718,
  },
  {
    id: 76,
    name: 'Greece',
    flag: '/images/countries/Flag_of_Greece.svg',
    iso2: 'GR',
    iso3: 'GRC',
    population: 10731726,
  },
  {
    id: 77,
    name: 'Greenland',
    flag: '/images/countries/Flag_of_Greenland.svg',
    iso2: 'GL',
    iso3: 'GRL',
    population: 56025,
  },
  {
    id: 78,
    name: 'Grenada',
    flag: '/images/countries/Flag_of_Grenada.svg',
    iso2: 'GD',
    iso3: 'GRD',
    population: 111454,
  },
  {
    id: 80,
    name: 'Guam',
    flag: '/images/countries/Flag_of_Guam.svg',
    iso2: 'GU',
    iso3: 'GUM',
    population: 165768,
  },
  {
    id: 81,
    name: 'Guatemala',
    flag: '/images/countries/Flag_of_Guatemala.svg',
    iso2: 'GT',
    iso3: 'GTM',
    population: 17247807,
  },
  {
    id: 83,
    name: 'Guinea',
    flag: '/images/countries/Flag_of_Guinea.svg',
    iso2: 'GN',
    iso3: 'GIN',
    population: 12414318,
  },
  {
    id: 84,
    name: 'Guinea-Bissau',
    flag: '/images/countries/Flag_of_Guinea-Bissau.svg',
    iso2: 'GW',
    iso3: 'GNB',
    population: 1874309,
  },
  {
    id: 85,
    name: 'Guyana',
    flag: '/images/countries/Flag_of_Guyana.svg',
    iso2: 'GY',
    iso3: 'GUY',
    population: 779004,
  },
  {
    id: 86,
    name: 'Haiti',
    flag: '/images/countries/Flag_of_Haiti.svg',
    iso2: 'HT',
    iso3: 'HTI',
    population: 11123176,
  },
  {
    id: 89,
    name: 'Honduras',
    flag: '/images/countries/Naval_Ensign_of_Honduras.svg',
    iso2: 'HN',
    iso3: 'HND',
    population: 9587522,
  },
  {
    id: 90,
    name: 'Hong Kong',
    flag: '/images/countries/Flag_of_Hong_Kong.svg',
    iso2: 'HK',
    iso3: 'HKG',
    population: 7451000,
  },
  {
    id: 91,
    name: 'Hungary',
    flag: '/images/countries/Flag_of_Hungary.svg',
    iso2: 'HU',
    iso3: 'HUN',
    population: 9775564,
  },
  {
    id: 92,
    name: 'Iceland',
    flag: '/images/countries/Flag_of_Iceland.svg',
    iso2: 'IS',
    iso3: 'ISL',
    population: 352721,
  },
  {
    id: 93,
    name: 'India',
    flag: 'images/countries/Flag_of_India.svg',
    iso2: 'IN',
    iso3: 'IND',
    population: 1352617328,
  },
  {
    id: 94,
    name: 'Indonesia',
    flag: '/images/countries/Flag_of_Indonesia.svg',
    iso2: 'ID',
    iso3: 'IDN',
    population: 267663435,
  },
  {
    id: 95,
    name: 'Iran',
    flag: ' /images/countries/Flag_of_Iran.svg',
    iso2: 'IR',
    iso3: 'IRN',
    population: 81800269,
  },
  {
    id: 96,
    name: 'Iraq',
    flag: '/images/countries/Flag_of_Iraq.svg',
    iso2: 'IQ',
    iso3: 'IRQ',
    population: 38433600,
  },
  {
    id: 97,
    name: 'Ireland',
    flag: '/images/countries/Flag_of_Ireland.svg',
    iso2: 'IE',
    iso3: 'IRL',
    population: 4867309,
  },
  {
    id: 98,
    name: 'Isle of Man',
    flag: '/images/countries/Flag_of_the_Isle_of_Man.svg',
    iso2: 'IM',
    iso3: 'IMN',
    population: 84077,
  },
  {
    id: 99,
    name: 'Israel',
    flag: '/images/countries/Flag_of_Israel.svg',
    iso2: 'IL',
    iso3: 'ISR',
    population: 8882800,
  },
  {
    id: 100,
    name: 'Italy',
    flag: 'images/countries/Flag_of_Italy.svg',
    iso2: 'IT',
    iso3: 'ITA',
    population: 60421760,
  },
  {
    id: 101,
    name: 'Jamaica',
    flag: '/images/countries/Flag_of_Jamaica.svg',
    iso2: 'JM',
    iso3: 'JAM',
    population: 2934855,
  },
  {
    id: 102,
    name: 'Japan',
    flag: 'images/countries/Flag_of_Japan.svg',
    iso2: 'JP',
    iso3: 'JPN',
    population: 126529100,
  },
  {
    id: 104,
    name: 'Jordan',
    flag: '/images/countries/Flag_of_Jordan.svg',
    iso2: 'JO',
    iso3: 'JOR',
    population: 9956011,
  },
  {
    id: 105,
    name: 'Kazakhstan',
    flag: '/images/countries/Flag_of_Kazakhstan.svg',
    iso2: 'KZ',
    iso3: 'KAZ',
    population: 18272430,
  },
  {
    id: 106,
    name: 'Kenya',
    flag: '/images/countries/Flag_of_Kenya.svg',
    iso2: 'KE',
    iso3: 'KEN',
    population: 51393010,
  },
  {
    id: 107,
    name: 'Kiribati',
    flag: '/images/countries/Flag_of_Kiribati.svg',
    iso2: 'KI',
    iso3: 'KIR',
    population: 115847,
  },
  {
    id: 108,
    name: 'Kuwait',
    flag: '/images/countries/Flag_of_Kuwait.svg',
    iso2: 'KW',
    iso3: 'KWT',
    population: 4137309,
  },
  {
    id: 109,
    name: 'Kyrgyzstan',
    flag: '/images/countries/Flag_of_Kyrgyzstan.svg',
    iso2: 'KG',
    iso3: 'KGZ',
    population: 6322800,
  },
  {
    id: 110,
    name: 'Laos',
    flag: '/images/countries/Flag_of_Laos.svg',
    iso2: 'LA',
    iso3: 'LAO',
    population: 7061507,
  },
  {
    id: 111,
    name: 'Latvia',
    flag: '/images/countries/Flag_of_Latvia.svg',
    iso2: 'LV',
    iso3: 'LVA',
    population: 1927174,
  },
  {
    id: 112,
    name: 'Lebanon',
    flag: '/images/countries/Flag_of_Lebanon.svg',
    iso2: 'LB',
    iso3: 'LBN',
    population: 6848925,
  },
  {
    id: 113,
    name: 'Lesotho',
    flag: '/images/countries/Flag_of_Lesotho.svg',
    iso2: 'LS',
    iso3: 'LSO',
    population: 2108132,
  },
  {
    id: 114,
    name: 'Liberia',
    flag: '/images/countries/Flag_of_Liberia.svg',
    iso2: 'LR',
    iso3: 'LBR',
    population: 4818977,
  },
  {
    id: 115,
    name: 'Liechtenstein',
    flag: '/images/countries/Flag_of_Liechtenstein.svg',
    iso2: 'LI',
    iso3: 'LIE',
    population: 37910,
  },
  {
    id: 116,
    name: 'Lithuania',
    flag: '/images/countries/Flag_of_Lithuania.svg',
    iso2: 'LT',
    iso3: 'LTU',
    population: 2801543,
  },
  {
    id: 117,
    name: 'Luxembourg',
    flag: '/images/countries/Flag_of_Luxembourg.svg',
    iso2: 'LU',
    iso3: 'LUX',
    population: 607950,
  },
  {
    id: 118,
    name: 'Macau',
    flag: '/images/countries/Flag_of_Macau.svg',
    iso2: 'MO',
    iso3: 'MAC',
    population: 631636,
  },
  {
    id: 119,
    name: 'Madagascar',
    flag: '/images/countries/Flag_of_Madagascar.svg',
    iso2: 'MG',
    iso3: 'MDG',
    population: 26262368,
  },
  {
    id: 120,
    name: 'Malawi',
    flag: '/images/countries/Flag_of_Malawi.svg',
    iso2: 'MW',
    iso3: 'MWI',
    population: 18143315,
  },
  {
    id: 121,
    name: 'Malaysia',
    flag: '/images/countries/Flag_of_Malaysia.svg',
    iso2: 'MY',
    iso3: 'MYS',
    population: 31528585,
  },
  {
    id: 122,
    name: 'Maldives',
    flag: '/images/countries/Flag_of_Maldives.svg',
    iso2: 'MV',
    iso3: 'MDV',
    population: 515696,
  },
  {
    id: 123,
    name: 'Mali',
    flag: '/images/countries/Flag_of_Mali.svg',
    iso2: 'ML',
    iso3: 'MLI',
    population: 19077690,
  },
  {
    id: 124,
    name: 'Malta',
    flag: '/images/countries/Flag_of_Malta.svg',
    iso2: 'MT',
    iso3: 'MLT',
    population: 484630,
  },
  {
    id: 125,
    name: 'Marshall Islands',
    flag: '/images/countries/Flag_of_the_Marshall_Islands.svg',
    iso2: 'MH',
    iso3: 'MHL',
    population: 58413,
  },
  {
    id: 127,
    name: 'Mauritania',
    flag: '/images/countries/Flag_of_Mauritania.svg',
    iso2: 'MR',
    iso3: 'MRT',
    population: 4403319,
  },
  {
    id: 128,
    name: 'Mauritius',
    flag: '/images/countries/Flag_of_Mauritius.svg',
    iso2: 'MU',
    iso3: 'MUS',
    population: 1265303,
  },
  {
    id: 130,
    name: 'Mexico',
    flag: '/images/countries/Flag_of_Mexico.svg',
    iso2: 'MX',
    iso3: 'MEX',
    population: 126190788,
  },
  {
    id: 131,
    name: 'Monaco',
    flag: '/images/countries/Flag_of_Monaco.svg',
    iso2: 'MC',
    iso3: 'MCO',
    population: 38682,
  },
  {
    id: 132,
    name: 'Mongolia',
    flag: '/images/countries/Flag_of_Mongolia.svg',
    iso2: 'MN',
    iso3: 'MNG',
    population: 3170208,
  },
  {
    id: 133,
    name: 'Montenegro',
    flag: '/images/countries/Flag_of_Montenegro.svg',
    iso2: 'ME',
    iso3: 'MNE',
    population: 622227,
  },
  {
    id: 135,
    name: 'Morocco',
    flag: '/images/countries/Flag_of_Morocco.svg',
    iso2: 'MA',
    iso3: 'MAR',
    population: 36029138,
  },
  {
    id: 136,
    name: 'Mozambique',
    flag: '/images/countries/Flag_of_Mozambique.svg',
    iso2: 'MZ',
    iso3: 'MOZ',
    population: 29495962,
  },
  {
    id: 137,
    name: 'Myanmar',
    flag: '/images/countries/Flag_of_Myanmar.svg',
    iso2: 'MM',
    iso3: 'MMR',
    population: 53708395,
  },
  {
    id: 138,
    name: 'Namibia',
    flag: '/images/countries/Flag_of_Namibia.svg',
    iso2: 'NA',
    iso3: 'NAM',
    population: 2448255,
  },
  {
    id: 139,
    name: 'Nauru',
    flag: '/images/countries/Flag_of_Nauru.svg',
    iso2: 'NR',
    iso3: 'NRU',
    population: 12704,
  },
  {
    id: 140,
    name: 'Nepal',
    flag: '/images/countries/Flag_of_Nepal.svg',
    iso2: 'NP',
    iso3: 'NPL',
    population: 28087871,
  },
  {
    id: 141,
    name: 'Netherlands',
    flag: '/images/countries/Flag_of_the_Netherlands.svg',
    iso2: 'NL',
    iso3: 'NLD',
    population: 17231624,
  },
  {
    id: 142,
    name: 'New Caledonia',
    flag: '/images/countries/Flags_of_New_Caledonia.svg',
    iso2: 'NC',
    iso3: 'NCL',
    population: 284060,
  },
  {
    id: 143,
    name: 'New Zealand',
    flag: '/images/countries/Flag_of_New_Zealand.svg',
    iso2: 'NZ',
    iso3: 'NZL',
    population: 4841000,
  },
  {
    id: 144,
    name: 'Nicaragua',
    flag: '/images/countries/Flag_of_Nicaragua.svg',
    iso2: 'NI',
    iso3: 'NIC',
    population: 6465513,
  },
  {
    id: 145,
    name: 'Niger',
    flag: '/images/countries/Flag_of_Niger.svg',
    iso2: 'NE',
    iso3: 'NER',
    population: 22442948,
  },
  {
    id: 146,
    name: 'Nigeria',
    flag: '/images/countries/Flag_of_Nigeria.svg',
    iso2: 'NG',
    iso3: 'NGA',
    population: 195874740,
  },
  {
    id: 149,
    name: 'Northern Mariana Islands',
    flag: '/images/countries/Flag_of_the_Northern_Mariana_Islands.svg',
    iso2: 'MP',
    iso3: 'MNP',
    population: 56882,
  },
  {
    id: 150,
    name: 'Norway',
    flag: '/images/countries/Flag_of_Norway.svg',
    iso2: 'NO',
    iso3: 'NOR',
    population: 5311916,
  },
  {
    id: 151,
    name: 'Oman',
    flag: '/images/countries/Flag_of_Oman.svg',
    iso2: 'OM',
    iso3: 'OMN',
    population: 4829483,
  },
  {
    id: 152,
    name: 'Pakistan',
    flag: '/images/countries/Flag_of_Pakistan.svg',
    iso2: 'PK',
    iso3: 'PAK',
    population: 212215030,
  },
  {
    id: 153,
    name: 'Palau',
    flag: '/images/countries/Flag_of_Palau.svg',
    iso2: 'PW',
    iso3: 'PLW',
    population: 17907,
  },
  {
    id: 154,
    name: 'Panama',
    flag: '/images/countries/Flag_of_Panama.svg',
    iso2: 'PA',
    iso3: 'PAN',
    population: 4176873,
  },
  {
    id: 155,
    name: 'Papua New Guinea',
    flag: '/images/countries/Flag_of_Papua_New_Guinea.svg',
    iso2: 'PG',
    iso3: 'PNG',
    population: 8606316,
  },
  {
    id: 156,
    name: 'Paraguay',
    flag: '/images/countries/Flag_of_Paraguay.svg',
    iso2: 'PY',
    iso3: 'PRY',
    population: 6956071,
  },
  {
    id: 157,
    name: 'Peru',
    flag: '/images/countries/Flag_of_Peru.svg',
    iso2: 'PE',
    iso3: 'PER',
    population: 31989256,
  },
  {
    id: 158,
    name: 'Philippines',
    flag: '/images/countries/Flag_of_the_Philippines.svg',
    iso2: 'PH',
    iso3: 'PHL',
    population: 106651922,
  },
  {
    id: 160,
    name: 'Poland',
    flag: 'images/countries/Flag_of_Poland.svg',
    iso2: 'PL',
    iso3: 'POL',
    population: 37974750,
  },
  {
    id: 161,
    name: 'Portugal',
    flag: '/images/countries/Flag_of_Portugal.svg',
    iso2: 'PT',
    iso3: 'PRT',
    population: 10283822,
  },
  {
    id: 162,
    name: 'Puerto Rico',
    flag: '/images/countries/Flag_of_Puerto_Rico.svg',
    iso2: 'PR',
    iso3: 'PRI',
    population: 3195153,
  },
  {
    id: 163,
    name: 'Qatar',
    flag: '/images/countries/Flag_of_Qatar.svg',
    iso2: 'QA',
    iso3: 'QAT',
    population: 2781677,
  },
  {
    id: 165,
    name: 'Romania',
    flag: '/images/countries/Flag_of_Romania.svg',
    iso2: 'RO',
    iso3: 'ROU',
    population: 19466145,
  },
  {
    id: 166,
    name: 'Rwanda',
    flag: '/images/countries/Flag_of_Rwanda.svg',
    iso2: 'RW',
    iso3: 'RWA',
    population: 12301939,
  },
  {
    id: 167,
    name: 'Saint Kitts and Nevis',
    flag: '/images/countries/Flag_of_Saint_Kitts_and_Nevis.svg',
    iso2: 'KN',
    iso3: 'KNA',
    population: 52441,
  },
  {
    id: 168,
    name: 'Saint Lucia',
    flag: '/images/countries/Flag_of_Saint_Lucia.svg',
    iso2: 'LC',
    iso3: 'LCA',
    population: 181889,
  },
  {
    id: 170,
    name: 'Saint Vincent and the Grenadines',
    flag: '/images/countries/Flag_of_Saint_Vincent_and_the_Grenadines.svg',
    iso2: 'VC',
    iso3: 'VCT',
    population: 110210,
  },
  {
    id: 171,
    name: 'Samoa',
    flag: '/images/countries/Flag_of_Samoa.svg',
    iso2: 'WS',
    iso3: 'WSM',
    population: 196130,
  },
  {
    id: 172,
    name: 'San Marino',
    flag: '/images/countries/Flag_of_San_Marino.svg',
    iso2: 'SM',
    iso3: 'SMR',
    population: 33785,
  },
  {
    id: 173,
    name: 'Sao Tome and Principe',
    flag: '/images/countries/Flag_of_Sao.svg',
    iso2: 'ST',
    iso3: 'STP',
    population: 211028,
  },
  {
    id: 174,
    name: 'Saudi Arabia',
    flag: '/images/countries/Flag_of_Saudi_Arabia.svg',
    iso2: 'SA',
    iso3: 'SAU',
    population: 33699947,
  },
  {
    id: 175,
    name: 'Senegal',
    flag: '/images/countries/Flag_of_Senegal.svg',
    iso2: 'SN',
    iso3: 'SEN',
    population: 15854360,
  },
  {
    id: 176,
    name: 'Serbia',
    flag: '/images/countries/Flag_of_Serbia.svg',
    iso2: 'RS',
    iso3: 'SRB',
    population: 6982604,
  },
  {
    id: 177,
    name: 'Seychelles',
    flag: '/images/countries/Flag_of_Seychelles.svg',
    iso2: 'SC',
    iso3: 'SYC',
    population: 96762,
  },
  {
    id: 178,
    name: 'Sierra Leone',
    flag: '/images/countries/Flag_of_Sierra_Leone.svg',
    iso2: 'SL',
    iso3: 'SLE',
    population: 7650154,
  },
  {
    id: 179,
    name: 'Singapore',
    flag: '/images/countries/Flag_of_Singapore.svg',
    iso2: 'SG',
    iso3: 'SGP',
    population: 5638676,
  },
  {
    id: 180,
    name: 'Slovakia',
    flag: '/images/countries/Flag_of_Slovakia.svg',
    iso2: 'SK',
    iso3: 'SVK',
    population: 5446771,
  },
  {
    id: 181,
    name: 'Slovenia',
    flag: '/images/countries/Flag_of_Slovenia.svg',
    iso2: 'SI',
    iso3: 'SVN',
    population: 2073894,
  },
  {
    id: 182,
    name: 'Solomon Islands',
    flag: '/images/countries/Flag_of_the_Solomon_Islands.svg',
    iso2: 'SB',
    iso3: 'SLB',
    population: 652858,
  },
  {
    id: 183,
    name: 'Somalia',
    flag: '/images/countries/Flag_of_Somalia.svg',
    iso2: 'SO',
    iso3: 'SOM',
    population: 15008154,
  },
  {
    id: 184,
    name: 'South Africa',
    flag: '/images/countries/Flag_of_South_Africa.svg',
    iso2: 'ZA',
    iso3: 'ZAF',
    population: 57779622,
  },
  {
    id: 186,
    name: 'Spain',
    flag: 'images/countries/Flag_of_Spain.svg',
    iso2: 'ES',
    iso3: 'ESP',
    population: 46796540,
  },
  {
    id: 187,
    name: 'Sri Lanka',
    flag: '/images/countries/Flag_of_Sri_Lanka.svg',
    iso2: 'LK',
    iso3: 'LKA',
    population: 21670000,
  },
  {
    id: 188,
    name: 'Sudan',
    flag: '/images/countries/Flag_of_Sudan.svg',
    iso2: 'SD',
    iso3: 'SDN',
    population: 41801533,
  },
  {
    id: 189,
    name: 'Suriname',
    flag: '/images/countries/Flag_of_Suriname.svg',
    iso2: 'SR',
    iso3: 'SUR',
    population: 575991,
  },
  {
    id: 190,
    name: 'Swaziland',
    flag: '/images/countries/Flag_of_Eswatini.svg',
    iso2: 'SZ',
    iso3: 'SWZ',
    population: 1136191,
  },
  {
    id: 191,
    name: 'Sweden',
    flag: '/images/countries/Flag_of_Sweden.svg',
    iso2: 'SE',
    iso3: 'SWE',
    population: 10175214,
  },
  {
    id: 192,
    name: 'Switzerland',
    flag: '/images/countries/Flag_of_Switzerland.svg',
    iso2: 'CH',
    iso3: 'CHE',
    population: 8513227,
  },
  {
    id: 193,
    name: 'Syria',
    flag: '/images/countries/Flag_of_Syria.svg',
    iso2: 'SY',
    iso3: 'SYR',
    population: 16906283,
  },
  {
    id: 195,
    name: 'Tajikistan',
    flag: '/images/countries/Flag_of_Tajikistan.svg',
    iso2: 'TJ',
    iso3: 'TJK',
    population: 9100837,
  },
  {
    id: 196,
    name: 'Thailand',
    flag: '/images/countries/Flag_of_Thailand.svg',
    iso2: 'TH',
    iso3: 'THA',
    population: 69428524,
  },
  {
    id: 197,
    name: 'Timor-Leste',
    flag: '/images/countries/Flag_of_East_Timor.svg',
    iso2: 'TL',
    iso3: 'TLS',
    population: 1267972,
  },
  {
    id: 198,
    name: 'Togo',
    flag: '/images/countries/Flag_of_Togo.svg',
    iso2: 'TG',
    iso3: 'TGO',
    population: 7889094,
  },
  {
    id: 200,
    name: 'Tonga',
    flag: '/images/countries/Flag_of_Tonga.svg',
    iso2: 'TO',
    iso3: 'TON',
    population: 103197,
  },
  {
    id: 201,
    name: 'Trinidad and Tobago',
    flag: '/images/countries/Flag_of_Trinidad_and_Tobago.svg',
    iso2: 'TT',
    iso3: 'TTO',
    population: 1389858,
  },
  {
    id: 202,
    name: 'Tunisia',
    flag: '/images/countries/Flag_of_Tunisia.svg',
    iso2: 'TN',
    iso3: 'TUN',
    population: 11565204,
  },
  {
    id: 203,
    name: 'Turkey',
    flag: '/images/countries/Flag_of_Turkey.svg',
    iso2: 'TR',
    iso3: 'TUR',
    population: 82319724,
  },
  {
    id: 204,
    name: 'Turkmenistan',
    flag: '/images/countries/Flag_of_Turkmenistan.svg',
    iso2: 'TM',
    iso3: 'TKM',
    population: 5850908,
  },
  {
    id: 205,
    name: 'Turks and Caicos Islands',
    flag: '/images/countries/Flag_of_the_Turks_and_Caicos_Islands.svg',
    iso2: 'TC',
    iso3: 'TCA',
    population: 37665,
  },
  {
    id: 206,
    name: 'Tuvalu',
    flag: '/images/countries/Flag_of_Tuvalu.svg',
    iso2: 'TV',
    iso3: 'TUV',
    population: 11508,
  },
  {
    id: 207,
    name: 'Uganda',
    flag: '/images/countries/Flag_of_Uganda.svg',
    iso2: 'UG',
    iso3: 'UGA',
    population: 42723139,
  },
  {
    id: 208,
    name: 'Ukraine',
    flag: '/images/countries/Flag_of_Ukraine.svg',
    iso2: 'UA',
    iso3: 'UKR',
    population: 44622516,
  },
  {
    id: 209,
    name: 'United Arab Emirates',
    flag: '/images/countries/Flag_of_the_United_Arab_Emirates.svg',
    iso2: 'AE',
    iso3: 'ARE',
    population: 9630959,
  },
  {
    id: 210,
    name: 'United Kingdom',
    flag: '/images/countries/Flag_of_the_United_Kingdom.svg',
    iso2: 'GB',
    iso3: 'GBR',
    population: 66460344,
  },
  {
    id: 211,
    name: 'United States',
    flag: 'images/countries/Flag_of_the_United_States.svg',
    iso2: 'US',
    iso3: 'USA',
    population: 326687501,
  },
  {
    id: 213,
    name: 'Uruguay',
    flag: '/images/countries/Flag_of_Uruguay.svg',
    iso2: 'UY',
    iso3: 'URY',
    population: 3449299,
  },
  {
    id: 214,
    name: 'Uzbekistan',
    flag: '/images/countries/Flag_of_Uzbekistan.svg',
    iso2: 'UZ',
    iso3: 'UZB',
    population: 32955400,
  },
  {
    id: 215,
    name: 'Vanuatu',
    flag: '/images/countries/Flag_of_Vanuatu.svg',
    iso2: 'VU',
    iso3: 'VUT',
    population: 292680,
  },
  {
    id: 216,
    name: 'Vietnam',
    flag: '/images/countries/Flag_of_Vietnam.svg',
    iso2: 'VN',
    iso3: 'VNM',
    population: 95540395,
  },
  {
    id: 218,
    name: 'Yemen',
    flag: '/images/countries/Flag_of_Yemen.svg',
    iso2: 'YE',
    iso3: 'YEM',
    population: 28498687,
  },
  {
    id: 219,
    name: 'Zambia',
    flag: '/images/countries/Flag_of_Zambia.svg',
    iso2: 'ZM',
    iso3: 'ZMB',
    population: 17351822,
  },
  {
    id: 220,
    name: 'Zimbabwe',
    flag: '/images/countries/Flag_of_Zimbabwe.svg',
    iso2: 'ZW',
    iso3: 'ZWE',
    population: 14439018,
  },
];
export default countries;
