export const leaderboard = [
  {
    id: 6,
    name: 'upbeat-ball227',
    country: 'Kenya',
    highestScore: 102,
    hintsAvailable: 2,
  },
  {
    id: 2,
    name: 'elegant-oasis928',
    country: 'Nigeria',
    highestScore: 99,
    hintsAvailable: 36,
  },
  {
    id: 5,
    name: 'witty-xylophone399',
    country: 'Malaysia',
    highestScore: 99,
    hintsAvailable: 6,
  },
  {
    id: 33,
    name: 'noble-moon92',
    country: 'Vietnam',
    highestScore: 98,
    hintsAvailable: 9,
  },
  {
    id: 31,
    name: 'innovative-quilt805',
    country: 'Malaysia',
    highestScore: 95,
    hintsAvailable: 38,
  },
  {
    id: 45,
    name: 'open-minded-volcano65',
    country: 'South Africa',
    highestScore: 95,
    hintsAvailable: 7,
  },
  {
    id: 21,
    name: 'quick-witted-snake125',
    country: 'India',
    highestScore: 92,
    hintsAvailable: 26,
  },
  {
    id: 34,
    name: 'zealous-night450',
    country: 'Indonesia',
    highestScore: 92,
    hintsAvailable: 39,
  },
  {
    id: 37,
    name: 'unassuming-island417',
    country: 'South Korea',
    highestScore: 92,
    hintsAvailable: 27,
  },
  {
    id: 44,
    name: 'passionate-tree814',
    country: 'Thailand',
    highestScore: 92,
    hintsAvailable: 20,
  },
  {
    id: 12,
    name: 'honest-ball61',
    country: 'Mexico',
    highestScore: 87,
    hintsAvailable: 18,
  },
  {
    id: 15,
    name: 'honest-dolphin510',
    country: 'Indonesia',
    highestScore: 84,
    hintsAvailable: 5,
  },
  {
    id: 25,
    name: 'resourceful-xylophone385',
    country: 'USA',
    highestScore: 84,
    hintsAvailable: 23,
  },
  {
    id: 39,
    name: 'wise-lemon663',
    country: 'India',
    highestScore: 84,
    hintsAvailable: 32,
  },
  {
    id: 42,
    name: 'unassuming-flower235',
    country: 'Vietnam',
    highestScore: 81,
    hintsAvailable: 21,
  },
  {
    id: 3,
    name: 'vivacious-waterfall460',
    country: 'Brazil',
    highestScore: 78,
    hintsAvailable: 10,
  },
  {
    id: 9,
    name: 'versatile-house171',
    country: 'Australia',
    highestScore: 78,
    hintsAvailable: 35,
  },
  {
    id: 11,
    name: 'friendly-quilt499',
    country: 'Canada',
    highestScore: 76,
    hintsAvailable: 4,
  },
  {
    id: 27,
    name: 'youthful-guitar406',
    country: 'Australia',
    highestScore: 76,
    hintsAvailable: 4,
  },
  {
    id: 30,
    name: 'diligent-night474',
    country: 'Ghana',
    highestScore: 76,
    hintsAvailable: 11,
  },
  {
    id: 13,
    name: 'wise-yogurt300',
    country: 'Canada',
    highestScore: 73,
    hintsAvailable: 21,
  },
  {
    id: 17,
    name: 'ambitious-guitar317',
    country: 'Thailand',
    highestScore: 69,
    hintsAvailable: 8,
  },
  {
    id: 38,
    name: 'generous-yogurt310',
    country: 'India',
    highestScore: 69,
    hintsAvailable: 24,
  },
  {
    id: 36,
    name: 'wise-quilt138',
    country: 'South Korea',
    highestScore: 67,
    hintsAvailable: 32,
  },
  {
    id: 48,
    name: 'zany-xylophone546',
    country: 'South Korea',
    highestScore: 66,
    hintsAvailable: 2,
  },
  {
    id: 23,
    name: 'modest-yacht130',
    country: 'India',
    highestScore: 64,
    hintsAvailable: 7,
  },
  {
    id: 46,
    name: 'brave-rain802',
    country: 'South Korea',
    highestScore: 57,
    hintsAvailable: 28,
  },
  {
    id: 1,
    name: 'kind-airplane718',
    country: 'Malaysia',
    highestScore: 52,
    hintsAvailable: 40,
  },
  {
    id: 24,
    name: 'fierce-volcano388',
    country: 'Nigeria',
    highestScore: 52,
    hintsAvailable: 40,
  },
  {
    id: 41,
    name: 'sensible-lemon832',
    country: 'USA',
    highestScore: 51,
    hintsAvailable: 12,
  },
  {
    id: 47,
    name: 'brave-forest704',
    country: 'Indonesia',
    highestScore: 51,
    hintsAvailable: 5,
  },
  {
    id: 29,
    name: 'versatile-penguin545',
    country: 'South Korea',
    highestScore: 46,
    hintsAvailable: 6,
  },
  {
    id: 49,
    name: 'versatile-umbrella295',
    country: 'Thailand',
    highestScore: 46,
    hintsAvailable: 14,
  },
  {
    id: 26,
    name: 'elegant-dog773',
    country: 'Vietnam',
    highestScore: 45,
    hintsAvailable: 38,
  },
  {
    id: 32,
    name: 'sincere-tiger162',
    country: 'Brazil',
    highestScore: 45,
    hintsAvailable: 12,
  },
  {
    id: 20,
    name: 'passionate-jacket498',
    country: 'Kenya',
    highestScore: 43,
    hintsAvailable: 12,
  },
  {
    id: 18,
    name: 'passionate-yacht556',
    country: 'USA',
    highestScore: 41,
    hintsAvailable: 34,
  },
  {
    id: 22,
    name: 'sensible-umbrella632',
    country: 'Indonesia',
    highestScore: 39,
    hintsAvailable: 24,
  },
  {
    id: 43,
    name: 'adventurous-jungle386',
    country: 'India',
    highestScore: 39,
    hintsAvailable: 11,
  },
  {
    id: 50,
    name: 'noble-key256',
    country: 'Ghana',
    highestScore: 38,
    hintsAvailable: 22,
  },
  {
    id: 4,
    name: 'loyal-yogurt411',
    country: 'Ghana',
    highestScore: 37,
    hintsAvailable: 26,
  },
  {
    id: 10,
    name: 'trustworthy-forest703',
    country: 'Kenya',
    highestScore: 37,
    hintsAvailable: 5,
  },
  {
    id: 35,
    name: 'witty-quilt404',
    country: 'Mexico',
    highestScore: 34,
    hintsAvailable: 31,
  },
  {
    id: 14,
    name: 'zany-key467',
    country: 'Ghana',
    highestScore: 33,
    hintsAvailable: 32,
  },
  {
    id: 19,
    name: 'open-minded-yacht458',
    country: 'Nigeria',
    highestScore: 30,
    hintsAvailable: 4,
  },
  {
    id: 16,
    name: 'sincere-kite135',
    country: 'Vietnam',
    highestScore: 23,
    hintsAvailable: 26,
  },
  {
    id: 40,
    name: 'resilient-volcano90',
    country: 'Thailand',
    highestScore: 23,
    hintsAvailable: 9,
  },
  {
    id: 8,
    name: 'trustworthy-airplane926',
    country: 'Canada',
    highestScore: 20,
    hintsAvailable: 28,
  },
  {
    id: 7,
    name: 'brave-queen345',
    country: 'South Korea',
    highestScore: 19,
    hintsAvailable: 32,
  },
  {
    id: 28,
    name: 'thoughtful-jungle584',
    country: 'Vietnam',
    highestScore: 12,
    hintsAvailable: 16,
  },
];
